name: Build and Push Docker image with YYYY.M.N Tag

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manual trigger from GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout repository with full history and tags
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up version tag
        id: tag
        run: |
          git fetch --tags  # Ensure tags are available

          YEAR=$(date +%Y)
          MONTH=$(date +%-m)
          PREFIX="${YEAR}.${MONTH}."

          # Find latest N for current month
          LAST=$(git tag -l "${PREFIX}*" | sed "s/^${PREFIX}//" | sort -nr | head -n 1)

          if [[ -z "$LAST" ]]; then
            NEXT=1
          else
            NEXT=$((LAST + 1))
          fi

          VERSION="${YEAR}.${MONTH}.${NEXT}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Generated version: $VERSION"

      - name: Create and push Git tag
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git tag "${VERSION}"
          git push origin "${VERSION}"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/nek000/distrobox-work:${{ env.VERSION }}
